import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { doc, getDoc, deleteDoc } from "firebase/firestore";
import { firestore } from "../firebase";
import jsPDF from "jspdf";
import "jspdf-autotable";

const OneFarmerDetails = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [farmer, setFarmer] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchFarmer = async () => {
      try {
        const docRef = doc(firestore, "farmers", id);
        const docSnap = await getDoc(docRef);

        if (docSnap.exists()) {
          setFarmer(docSnap.data());
        } else {
          console.error("No such farmer!");
        }
      } catch (error) {
        console.error("Error fetching farmer:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchFarmer();
  }, [id]);

  const handleDelete = async () => {
    const confirm = window.confirm("Are you sure you want to delete this farmer?");
    if (!confirm) return;

    try {
      await deleteDoc(doc(firestore, "farmers", id));
      alert("Farmer deleted successfully.");
      navigate(-1);
    } catch (error) {
      console.error("Error deleting farmer:", error);
      alert("Failed to delete farmer.");
    }
  };

  const handleGeneratePDF = async () => {
  const doc = new jsPDF();
  
  // Add logo (replace with your actual image path or base64)
  const logoImg = new Image();
  logoImg.src = "cosmologo.png"; // ✅ Replace with your actual logo path (in /public folder or use base64)

  logoImg.onload = () => {
    doc.addImage(logoImg, "PNG", 14, 10, 30, 20); // x, y, width, height
    doc.setFontSize(18);
    doc.text("Farmer Details Report", 50, 20);
    doc.setFontSize(11);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 50, 26);

    // Table of farmer details
    doc.autoTable({
      startY: 40,
      head: [["Field", "Value"]],
      body: [
        ["Full Name", `${farmer.lastname}, ${farmer.firstname} ${farmer.middlename || ""}`],
        ["Farmer ID", farmer.farmerID],
        ["Gender", farmer.gender],
        ["Phone", farmer.phone],
        ["WhatsApp", farmer.whatsappNumber],
        ["State", farmer.state],
        ["LGA", farmer.localGovernment],
        ["Primary Crop", farmer.primaryCrop],
        ["Farm Ownership", farmer.farmOwnership],
        ["Farming Season", farmer.farmingSeason],
      ],
      styles: { fontSize: 11 },
      headStyles: { fillColor: [30, 58, 138] },
      didDrawPage: (data) => {
        // Footer
        const pageCount = doc.internal.getNumberOfPages();
        const pageSize = doc.internal.pageSize;
        const pageHeight = pageSize.height || pageSize.getHeight();

        doc.setFontSize(10);
        doc.text(
          `Page ${pageCount}`,
          data.settings.margin.left,
          pageHeight - 10
        );
        doc.text(
          "Generated by Farmers Record System",
          data.settings.margin.left + 80,
          pageHeight - 10
        );
      },
    });

    doc.save(`${farmer.firstname}_${farmer.lastname}_details.pdf`);
  };
};


  const handleEdit = () => {
    navigate(`/edit-farmer/${id}`);
  };

  if (loading) return <p>Loading farmer details...</p>;
  if (!farmer) return <p>Farmer not found.</p>;

  return (
    <div className="farmer-details-container">
      <h2>Farmer Details</h2>
      <button className="back-button" onClick={() => navigate("/FarmersList")}>← Back to List</button>

      <div className="details-box">
        <p><strong>Full Name:</strong> {farmer.lastname || "-"}, {farmer.firstname || "-"} {farmer.middlename || "-"}</p>
        <p><strong>Farmer ID:</strong> {farmer.farmerID || "-"}</p>
        <p><strong>Gender:</strong> {farmer.gender || "-"}</p>
        <p><strong>Date of Birth:</strong> {farmer.dateOfBirth || "-"}</p>
        <p><strong>Phone:</strong> {farmer.phone || "-"}</p>
        <p><strong>WhatsApp:</strong> {farmer.whatsappNumber || "-"}</p>
        <p><strong>Email:</strong> {farmer.email || "-"}</p>
        <p><strong>State:</strong> {farmer.state || "-"}</p>
        <p><strong>Local Government:</strong> {farmer.localGovernment || "-"}</p>
        <p><strong>Address:</strong> {farmer.address || "-"}</p>
        <p><strong>Crop Type:</strong> {farmer.primaryCrop || "-"}</p>
        <p><strong>Farm Ownership:</strong> {farmer.farmOwnership || "-"}</p>
        <p><strong>Farming Season:</strong> {farmer.farmingSeason || "-"}</p>
        <p><strong>Farm Size:</strong> {farmer.farmSize || "-"}</p>

        <div className="action-buttons">
          <button onClick={handleEdit} className="edit-btn">✏️ Edit</button>
          <button onClick={handleDelete} className="delete-btn">🗑️ Delete</button>
          <button onClick={handleGeneratePDF} className="pdf-btn">📄 Generate PDF</button>
        </div>
      </div>

      <style>{`
        .farmer-details-container {
          padding: 20px;
          background-color: #f9fafb;
          min-height: 100vh;
        }

        h2 {
          text-align: center;
          color: #1e3a8a;
        }

        .back-button {
          background-color: #1e3a8a;
          color: white;
          border: none;
          padding: 10px 20px;
          margin: 20px 0;
          border-radius: 4px;
          cursor: pointer;
        }

        .details-box {
          max-width: 700px;
          margin: 0 auto;
          background-color: white;
          padding: 20px;
          border-radius: 8px;
          box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        }

        .details-box p {
          margin: 10px 0;
          font-size: 16px;
        }

        .details-box strong {
          color: #1e3a8a;
        }

        .action-buttons {
          display: flex;
          gap: 10px;
          margin-top: 20px;
        }

        .edit-btn, .delete-btn, .pdf-btn {
          padding: 10px 15px;
          border: none;
          border-radius: 4px;
          cursor: pointer;
        }

        .edit-btn {
          background-color: #1e40af;
          color: white;
        }

        .delete-btn {
          background-color: #dc2626;
          color: white;
        }

        .pdf-btn {
          background-color: #059669;
          color: white;
        }
      `}</style>
    </div>
  );
};

export default OneFarmerDetails;
